// Candlestick Data
export const CANDLESTICK_DATA_REQUEST = 'CANDLESTICK_DATA_REQUEST';
export const CANDLESTICK_DATA_SUCCESS = 'CANDLESTICK_DATA_SUCCESS';
export const CANDLESTICK_DATA_FAIL = 'CANDLESTICK_DATA_FAIL';

// Line Chart Data
export const LINE_CHART_DATA_REQUEST = 'LINE_CHART_DATA_REQUEST';
export const LINE_CHART_DATA_SUCCESS = 'LINE_CHART_DATA_SUCCESS';
export const LINE_CHART_DATA_FAIL = 'LINE_CHART_DATA_FAIL';

// Bar Chart Data
export const BAR_CHART_DATA_REQUEST = 'BAR_CHART_DATA_REQUEST';
export const BAR_CHART_DATA_SUCCESS = 'BAR_CHART_DATA_SUCCESS';
export const BAR_CHART_DATA_FAIL = 'BAR_CHART_DATA_FAIL';

// Pie Chart Data
export const PIE_CHART_DATA_REQUEST = 'PIE_CHART_DATA_REQUEST';
export const PIE_CHART_DATA_SUCCESS = 'PIE_CHART_DATA_SUCCESS';
export const PIE_CHART_DATA_FAIL = 'PIE_CHART_DATA_FAIL';
